server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/storage}
      auto-index-creation: true
  codec:
    max-in-memory-size: 1MB
  servlet:
    http2: false

logging.level.reactor.netty: INFO
